# permissions for end users to view parameterstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parameterstore-viewer-role
rules:
- apiGroups:
  - ssm.aws
  resources:
  - parameterstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ssm.aws
  resources:
  - parameterstores/status
  verbs:
  - get
